[klibc] include: [sys/time.h] fix for Linux 3.5.1
From 3.5.1, <linux/time.h> does not even define FD_ZERO etc.

With Linux 3.5.1, 'make test' fails with:

  usr/klibc/tests/select.c: In function ‘main’:
  usr/klibc/tests/select.c:31:14: error: ‘FD_SETSIZE’ undeclared (first use in this function)
  usr/klibc/tests/select.c:31:14: note: each undeclared identifier is reported only once for each function it appears in

This is due to Linux commit 8ded2bbc1845e19c771eb55209aab166ef011243.
Handle it by making sure that FD_SETSIZE is defined.

Signed-off-by: Colin Watson <cjwatson@ubuntu.com>
Signed-off-by: maximilian attems <max@stro.at>